### ISSUE TITLE
[Critical bug] Infinity reconnection

### ISSUE THREAD

**Issue by n08i40k** [PhoenixFire6879/Modern-Brawl#7]
I trying connect to my server, and see this in console:
```
[DEBUG] Connecting to Mongo DataBase...
[DEBUG] Server started! Listening on 0.0.0.0:8082 
[DEBUG] Client connected! IP: ***.***.***.***
[SERVER] PacketID: 23457, Name: LobbyInfoMessage, Length: 37
[CLIENT] PacketID: 10101, Name: LoginMessage Length: 187 
[SERVER] PacketID: 20103, Name: LoginFailedMessage, Length: 281
[SERVER] PacketID: 20104, Name: LoginOkMessage, Length: 171
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/n08i40k/Рабочий стол/Modern-Brawl-2.0/Core/Networking/ClientThread.py", line 71, in run
    message.process(self.db)
  File "/home/n08i40k/Рабочий стол/Modern-Brawl-2.0/Protocol/Messages/Client/LoginMessage.py", line 59, in process
    OwnHomeDataMessage(self.client, self.player).send()
  File "/home/n08i40k/Рабочий стол/Modern-Brawl-2.0/ByteStream/Writer.py", line 59, in send
    self.client.send(self.buffer)
BrokenPipeError: [Errno 32] Broken pipe
```
How i can fix this?

**Comment by thecoolestfali** [comment]
писюн сломанный
